# fly.toml app configuration file generated for bence-portfolio on 2024-08-07T20:45:28Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "bence-portfolio"
primary_region = "lhr"  # London region for European users

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 2

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  tls_skip_verify = false

  [http_service.checks.headers]
    Content-Type = "application/json"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[processes]
  web = "node dist/main.js"

# Optional: Configure metrics and monitoring
[metrics]
  port = 9091
  path = "/metrics"